### ISSUE TITLE
Support test clock with pause and advance

### ISSUE THREAD

**Issue by afsalthaj** [vigoo/test-r#75]

**Comment by vigoo** [comment]
This is not really possible because there is no overrideable global "clock" abstraction. You cannot override what the standard time functions return or how sleep behaves.

**Comment by vigoo** [comment]
See https://tokio.rs/tokio/topics/testing

To support using `tokio::time::pause`, there should be
- a new test option to spawn a separate tokio runtime per test - this, however, should not be the default as it may not work well with some shared dependencies
- support for the `start_paused`
